//! Renders a Sashiko `Settings.toml` that routes the review through this bridge.

use std::path::PathBuf;

use anyhow::Result;
use clap::Args;

#[derive(Debug, Args)]
pub struct SettingsArgs {
    /// Base URL of the bridge, e.g. http://127.0.0.1:53421/v1
    #[arg(long)]
    pub base_url: String,
    /// Model identifier reported to Sashiko (the VS Code chat model id).
    #[arg(long)]
    pub model: String,
    /// Path to the kernel git repository under review.
    #[arg(long)]
    pub repository_path: String,
    /// Directory Sashiko uses for review worktrees.
    #[arg(long, default_value = "review_trees")]
    pub worktree_dir: String,
    /// Provider name; Sashiko accepts "openai-compatible" and "openai-compat".
    #[arg(long, default_value = "openai-compatible")]
    pub provider: String,
    #[arg(long, default_value_t = 128_000)]
    pub context_window_size: u64,
    #[arg(long, default_value_t = 16_384)]
    pub max_tokens: u64,
    #[arg(long, default_value_t = 100_000)]
    pub max_input_tokens: u64,
    #[arg(long, default_value_t = 1)]
    pub concurrency: u64,
    /// Write the rendered settings here instead of stdout.
    #[arg(long)]
    pub out: Option<PathBuf>,
}

fn toml_string(value: &str) -> String {
    let escaped = value
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n");
    format!("\"{escaped}\"")
}

pub fn render(args: &SettingsArgs) -> String {
    format!(
        r#"# Generated by the Sashiko VS Code extension. Edits are overwritten on regeneration.
#
# The AI provider points at a loopback bridge owned by the extension, which forwards
# every completion to the language model already configured in VS Code. No LLM_API_KEY
# is involved; the bearer token below is a per-session credential for the bridge only.

[ai]
provider = {provider}
model = {model}
max_input_tokens = {max_input_tokens}
temperature = 1.0

[ai.openai_compat]
base_url = {base_url}
context_window_size = {context_window_size}
max_tokens = {max_tokens}

[git]
repository_path = {repository_path}

[review]
concurrency = {concurrency}
worktree_dir = {worktree_dir}
"#,
        provider = toml_string(&args.provider),
        model = toml_string(&args.model),
        max_input_tokens = args.max_input_tokens,
        base_url = toml_string(&args.base_url),
        context_window_size = args.context_window_size,
        max_tokens = args.max_tokens,
        repository_path = toml_string(&args.repository_path),
        concurrency = args.concurrency,
        worktree_dir = toml_string(&args.worktree_dir),
    )
}

pub fn run(args: &SettingsArgs) -> Result<()> {
    let rendered = render(args);
    match &args.out {
        Some(path) => {
            if let Some(parent) = path.parent() {
                std::fs::create_dir_all(parent)?;
            }
            std::fs::write(path, rendered)?;
        }
        None => print!("{rendered}"),
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn escapes_windows_style_paths() {
        assert_eq!(toml_string(r"C:\src\linux"), r#""C:\\src\\linux""#);
    }
}
